language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
script:
  - "python setup.py test"
deploy:
  provider: pypi
  user: ...
  password: ...
  distributions: "sdist bdist_wheel"
  on:
    tags: true
